name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.25", "1.24", "1.23"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: false # depends on go.sum
      - run: go mod tidy
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_go_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: go generate ./test/ent && go mod tidy
      - run: go test -v
