name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.26, 1.25, 1.24, 1.23]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: false # depends on go.sum
      - run: |
          go mod tidy
          (cd adapters/pgx && go mod tidy)
          (cd adapters/ent && go mod tidy)
          (cd examples && go mod tidy)
          (cd adapter_tests && go mod tidy)
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_go_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.2 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: (cd adapters/ent && go generate ./test && go mod tidy)
      - run: go test -v ./...
      - run: (cd adapters/pgx && go test -v ./...)
      - run: (cd adapters/ent && go test -v ./...)
      - run: (cd examples && go test -v ./...)
      - run: (cd adapter_tests && go test -v ./...)
